"$schema" = 'https://starship.rs/config-schema.json'

format = """
$username\
$directory\
$git_branch\
$git_status\
$fill\
$c\
$elixir\
$elm\
$golang\
$haskell\
$java\
$julia\
$nim\
$rust\
$scala\
$conda\
$python\
$time\n\
\\$ 
"""

palette = "modus-operandi"

[palettes.modus-operandi]
overlay = '#ffffff'
red = '#a60000'
yellow = '#6f5500'
pink = '#7b435c'
aqua = '#0031a9'
cyan = '#005e8b'
purple = '#4a3a8a'
nord_bg = '#2e3440'
nord_fg = '#d8dee9'

[directory]
format = "\\[$path\\]"
style = "bg:nord_bg fg:aqua"
truncation_length = 0
truncate_to_repo = true
# truncation_symbol = "‚Ä¶/"

[directory.substitutions]
Documents = "Û∞àô"
Downloads = "ÔÄô "
Music = "ÔÄÅ "
Pictures = "ÔÄæ "

[fill]
style = "fg:overlay"
symbol = " "

[git_branch]
# format = "[ÓÇ∂](fg:overlay)[ $symbol $branch ]($style)[ÓÇ¥](fg:overlay) "
format = "\\[[$branch]($style)"
style = "bg:nord_bg fg:cyan"
symbol = "Ôêò"

[git_status]
disabled = false
style = "bg:nord_bg fg:red"
# format = '[ÓÇ∂](fg:nord_bg)([$all_status$ahead_behind]($style))[ÓÇ¥](fg:nord_bg) '
format = ' $all_status$ahead_behind\]'
up_to_date = '[ ‚úì ](bg:nord_bg fg:purple)'
untracked = '[?\($count\)](bg:nord_bg fg:yellow)'
stashed = '[\$](bg:nord_bg fg:purple)'
modified = '[!\($count\)](bg:nord_bg fg:yellow)'
renamed = '[¬ª\($count\)](bg:nord_bg fg:purple)'
deleted = '[‚úò\($count\)](style)'
staged = '[++\($count\)](bg:nord_bg fg:yellow)'
ahead = '[‚á°\(${count}\)](bg:nord_bg fg:cyan)'
diverged = '‚áï[\[](bg:nord_bg fg:purple)[‚á°\(${ahead_count}\)](bg:nord_bg fg:cyan)[‚á£\(${behind_count}\)](bg:nord_bg fg:pink)[\]](bg:nord_bg fg:purple)'
behind = '[‚á£\(${count}\)](bg:nord_bg fg:pink)'

[time]
disabled = false
# format = " [ÓÇ∂](fg:overlay)[ $time Û∞¥à ]($style)[ÓÇ¥](fg:overlay)"
format = "  [ $time]($style)"
style = "bg:nord_bg fg:yellow"
time_format = "%H:%M"
use_12hr = false

[username]
disabled = false
# format = "[ÓÇ∂](fg:overlay)[ Û∞ß± $user ]($style)[ÓÇ¥](fg:overlay) "
format = "[$user ]($style)"
show_always = true
style_root = "bg_nord fg:purple"
style_user = "bg:nord_bg fg:nord_fg"

# Languages

[c]
style = "bg_nord fg:aqua"
format = " [ÓÇ∂](fg:overlay)[ $symbol$version ]($style)[ÓÇ¥](fg:overlay)"
disabled = false
symbol = "Óòû "

[elixir]
style = "bg_nord fg:aqua"
format = " [ÓÇ∂](fg:overlay)[ $symbol$version ]($style)[ÓÇ¥](fg:overlay)"
disabled = false
symbol = "Óâµ "

[elm]
style = "bg_nord fg:aqua"
format = " [ÓÇ∂](fg:overlay)[ $symbol$version ]($style)[ÓÇ¥](fg:overlay)"
disabled = false
symbol = "Óò¨ "

[golang]
style = "bg_nord fg:aqua"
format = " [ÓÇ∂](fg:overlay)[ $symbol$version ]($style)[ÓÇ¥](fg:overlay)"
disabled = false
symbol = "Óòß "

[haskell]
style = "bg_nord fg:aqua"
format = " [ÓÇ∂](fg:overlay)[ $symbol$version ]($style)[ÓÇ¥](fg:overlay)"
disabled = false
symbol = "Óù∑ "

[java]
style = "bg_nord fg:aqua"
format = " [ÓÇ∂](fg:overlay)[ $symbol$version ]($style)[ÓÇ¥](fg:overlay)"
disabled = false
symbol = "Óâñ "

[julia]
style = "bg_nord fg:aqua"
format = " [ÓÇ∂](fg:overlay)[ $symbol$version ]($style)[ÓÇ¥](fg:overlay)"
disabled = false
symbol = "Óò§ "

[nodejs]
style = "bg_nord fg:aqua"
format = " [ÓÇ∂](fg:overlay)[ $symbol$version ]($style)[ÓÇ¥](fg:overlay)"
disabled = false
symbol = "Û∞éô "

[nim]
style = "bg_nord fg:aqua"
format = " [ÓÇ∂](fg:overlay)[ $symbol$version ]($style)[ÓÇ¥](fg:overlay)"
disabled = false
symbol = "Û∞Ü• "

[rust]
style = "bg_nord fg:aqua"
format = " [ÓÇ∂](fg:overlay)[ $symbol$version ]($style)[ÓÇ¥](fg:overlay)"
disabled = false
symbol = "Óû® "

[scala]
style = "bg_nord fg:aqua"
format = " [ÓÇ∂](fg:overlay)[ $symbol$version ]($style)[ÓÇ¥](fg:overlay)"
disabled = false
symbol = "Óú∑ "

[python]
style = "bg_nord fg:aqua"
format = " [ÓÇ∂](fg:overlay)[ $symbol$version ]($style)[ÓÇ¥](fg:overlay)"
disabled = false
symbol = 'Óúº '

[conda]
style = "bg_nord fg:aqua"
format = " [ÓÇ∂](fg:overlay)[ $symbol$environment ]($style)[ÓÇ¥](fg:overlay)"
disabled = false
symbol = 'üÖí '
